### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by pipedream**
Would like to see a license on this so we can package it for Debian. I put a GPL but can put another license if you prefer.

### CODE REVIEW

**Comment by bertoldia** [comment]
Thanks Jan. I'll also add this to my other gnome-shell extension in case you want to package it in Debian too.

**Comment by highvoltage** [comment]
Hey Bertoldia, would you mind doing a new release that contains the LICENSE file? thanks!

**Comment by bertoldia** [comment]
Hi Jonathan,

Finally done. Sorry for the delay.

Cheers,
axel.

**Comment by highvoltage** [comment]
Great, thanks! Your extension is now uploaded to unstable and will be available in the next Debian release as "gnome-shell-extension-trash" :)

**Comment by bertoldia** [comment]
Thanks yo!

**Pull request merged**
